import jsPDF from "jspdf";

export const downloadReceipt = (payment) => {

    const doc = new jsPDF("p", "mm", "a4");

    const GREEN = [22, 163, 74];
    const LIGHT_GREEN = [240, 253, 244];
    const DARK = [40, 40, 40];
    const GRAY = [120, 120, 120];

    // ================= Header =================

    doc.setFillColor(...GREEN);
    doc.rect(0, 0, 210, 35, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text("DONOR DUCK", 20, 16);

    doc.setFontSize(13);
    doc.text("Donation Payment Receipt", 20, 27);

    // Receipt Number

    doc.setFontSize(10);
    doc.text(`Receipt : ${payment.orderId}`, 135, 16);

    // ================= Receipt Card =================

    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(220);
    doc.roundedRect(15, 45, 180, 190, 4, 4, "FD");

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.setFontSize(17);
    doc.text("Payment Details", 25, 60);

    doc.setDrawColor(230);
    doc.line(25, 65, 185, 65);

    let y = 80;

    const row = (label, value) => {

        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(...GRAY);
        doc.text(label, 25, y);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(...DARK);
        doc.text(String(value), 90, y);

        y += 14;
    };

    row("Receipt Number", payment.orderId);

    row("Donor Name", payment.donorName);

    row("Organization", payment.organizationName);

    row("Project", payment.projectTitle);

    row(
        "Donation Amount",
        `Rs. ${Number(payment.amount).toLocaleString("en-IN", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
        })}`
    );

    row(
        "Donation Date",
        new Date(payment.createdAt).toLocaleString("en-IN")
    );

    // ================= Status =================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...GRAY);
    doc.text("Payment Status", 25, y);

    if (payment.status === "SUCCESS") {

        doc.setFillColor(220, 252, 231);

        doc.roundedRect(90, y - 6, 42, 10, 3, 3, "F");

        doc.setTextColor(22, 101, 52);

    } else {

        doc.setFillColor(254, 226, 226);

        doc.roundedRect(90, y - 6, 42, 10, 3, 3, "F");

        doc.setTextColor(185, 28, 28);

    }

    doc.text(payment.status, 100, y);

    y += 20;

    // ================= Thank You =================

    doc.setFillColor(...LIGHT_GREEN);
    doc.roundedRect(25, y, 160, 35, 4, 4, "F");

    doc.setTextColor(...GREEN);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("Thank You For Supporting This Cause!", 32, y + 12);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.setFontSize(11);

    doc.text(
        "Your donation helps us create a better future for people in need.",
        32,
        y + 22
    );

    doc.text(
        "We sincerely appreciate your generosity and support.",
        32,
        y + 30
    );

    // ================= Footer =================

    doc.setDrawColor(220);
    doc.line(15, 260, 195, 260);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.setFontSize(10);

    doc.text("Generated by Donor Duck", 20, 270);

    doc.text(
        new Date().toLocaleString("en-IN"),
        145,
        270
    );

    doc.save(`Donation_Receipt_${payment.orderId}.pdf`);

};